// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: data-ingestion.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_FAILED  MessageType = 0
	MessageType_SUCCESS MessageType = 1
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "FAILED",
		1: "SUCCESS",
	}
	MessageType_value = map[string]int32{
		"FAILED":  0,
		"SUCCESS": 1,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_data_ingestion_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_data_ingestion_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_data_ingestion_proto_rawDescGZIP(), []int{0}
}

type NotifyBFFRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyBFFRequest) Reset() {
	*x = NotifyBFFRequest{}
	mi := &file_data_ingestion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyBFFRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyBFFRequest) ProtoMessage() {}

func (x *NotifyBFFRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_ingestion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyBFFRequest.ProtoReflect.Descriptor instead.
func (*NotifyBFFRequest) Descriptor() ([]byte, []int) {
	return file_data_ingestion_proto_rawDescGZIP(), []int{0}
}

type NotifyBFFMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Type          MessageType            `protobuf:"varint,2,opt,name=type,proto3,enum=dataIngestion.MessageType" json:"type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyBFFMessage) Reset() {
	*x = NotifyBFFMessage{}
	mi := &file_data_ingestion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyBFFMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyBFFMessage) ProtoMessage() {}

func (x *NotifyBFFMessage) ProtoReflect() protoreflect.Message {
	mi := &file_data_ingestion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyBFFMessage.ProtoReflect.Descriptor instead.
func (*NotifyBFFMessage) Descriptor() ([]byte, []int) {
	return file_data_ingestion_proto_rawDescGZIP(), []int{1}
}

func (x *NotifyBFFMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NotifyBFFMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_FAILED
}

func (x *NotifyBFFMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *NotifyBFFMessage) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type NotifyBFFResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Type          MessageType            `protobuf:"varint,2,opt,name=type,proto3,enum=dataIngestion.MessageType" json:"type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyBFFResponse) Reset() {
	*x = NotifyBFFResponse{}
	mi := &file_data_ingestion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyBFFResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyBFFResponse) ProtoMessage() {}

func (x *NotifyBFFResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_ingestion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyBFFResponse.ProtoReflect.Descriptor instead.
func (*NotifyBFFResponse) Descriptor() ([]byte, []int) {
	return file_data_ingestion_proto_rawDescGZIP(), []int{2}
}

func (x *NotifyBFFResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NotifyBFFResponse) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_FAILED
}

func (x *NotifyBFFResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *NotifyBFFResponse) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

var File_data_ingestion_proto protoreflect.FileDescriptor

const file_data_ingestion_proto_rawDesc = "" +
	"\n" +
	"\x14data-ingestion.proto\x12\rdataIngestion\x1a\x1fgoogle/protobuf/timestamp.proto\"\x12\n" +
	"\x10NotifyBFFRequest\"\xd6\x01\n" +
	"\x10NotifyBFFMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12.\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1a.dataIngestion.MessageTypeR\x04type\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fcompleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\xd7\x01\n" +
	"\x11NotifyBFFResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12.\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1a.dataIngestion.MessageTypeR\x04type\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fcompleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt*&\n" +
	"\vMessageType\x12\n" +
	"\n" +
	"\x06FAILED\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x012a\n" +
	"\rDataIngestion\x12P\n" +
	"\tNotifyBFF\x12\x1f.dataIngestion.NotifyBFFRequest\x1a .dataIngestion.NotifyBFFResponse0\x01B:Z8github.com/vinaymanala/nationpulse-data-ingsetion-svc/pbb\x06proto3"

var (
	file_data_ingestion_proto_rawDescOnce sync.Once
	file_data_ingestion_proto_rawDescData []byte
)

func file_data_ingestion_proto_rawDescGZIP() []byte {
	file_data_ingestion_proto_rawDescOnce.Do(func() {
		file_data_ingestion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_ingestion_proto_rawDesc), len(file_data_ingestion_proto_rawDesc)))
	})
	return file_data_ingestion_proto_rawDescData
}

var file_data_ingestion_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_data_ingestion_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_data_ingestion_proto_goTypes = []any{
	(MessageType)(0),              // 0: dataIngestion.MessageType
	(*NotifyBFFRequest)(nil),      // 1: dataIngestion.NotifyBFFRequest
	(*NotifyBFFMessage)(nil),      // 2: dataIngestion.NotifyBFFMessage
	(*NotifyBFFResponse)(nil),     // 3: dataIngestion.NotifyBFFResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_data_ingestion_proto_depIdxs = []int32{
	0, // 0: dataIngestion.NotifyBFFMessage.type:type_name -> dataIngestion.MessageType
	4, // 1: dataIngestion.NotifyBFFMessage.created_at:type_name -> google.protobuf.Timestamp
	4, // 2: dataIngestion.NotifyBFFMessage.completed_at:type_name -> google.protobuf.Timestamp
	0, // 3: dataIngestion.NotifyBFFResponse.type:type_name -> dataIngestion.MessageType
	4, // 4: dataIngestion.NotifyBFFResponse.created_at:type_name -> google.protobuf.Timestamp
	4, // 5: dataIngestion.NotifyBFFResponse.completed_at:type_name -> google.protobuf.Timestamp
	1, // 6: dataIngestion.DataIngestion.NotifyBFF:input_type -> dataIngestion.NotifyBFFRequest
	3, // 7: dataIngestion.DataIngestion.NotifyBFF:output_type -> dataIngestion.NotifyBFFResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_data_ingestion_proto_init() }
func file_data_ingestion_proto_init() {
	if File_data_ingestion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_ingestion_proto_rawDesc), len(file_data_ingestion_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_ingestion_proto_goTypes,
		DependencyIndexes: file_data_ingestion_proto_depIdxs,
		EnumInfos:         file_data_ingestion_proto_enumTypes,
		MessageInfos:      file_data_ingestion_proto_msgTypes,
	}.Build()
	File_data_ingestion_proto = out.File
	file_data_ingestion_proto_goTypes = nil
	file_data_ingestion_proto_depIdxs = nil
}
