// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.3
// source: data-ingestion.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataIngestion_NotifyBFF_FullMethodName = "/dataIngestion.DataIngestion/NotifyBFF"
)

// DataIngestionClient is the client API for DataIngestion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition : DataIngestion Service
type DataIngestionClient interface {
	// Unary RPC - notifies the BFF layer upon process completes
	NotifyBFF(ctx context.Context, in *NotifyBFFRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NotifyBFFResponse], error)
}

type dataIngestionClient struct {
	cc grpc.ClientConnInterface
}

func NewDataIngestionClient(cc grpc.ClientConnInterface) DataIngestionClient {
	return &dataIngestionClient{cc}
}

func (c *dataIngestionClient) NotifyBFF(ctx context.Context, in *NotifyBFFRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NotifyBFFResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataIngestion_ServiceDesc.Streams[0], DataIngestion_NotifyBFF_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NotifyBFFRequest, NotifyBFFResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataIngestion_NotifyBFFClient = grpc.ServerStreamingClient[NotifyBFFResponse]

// DataIngestionServer is the server API for DataIngestion service.
// All implementations must embed UnimplementedDataIngestionServer
// for forward compatibility.
//
// Service definition : DataIngestion Service
type DataIngestionServer interface {
	// Unary RPC - notifies the BFF layer upon process completes
	NotifyBFF(*NotifyBFFRequest, grpc.ServerStreamingServer[NotifyBFFResponse]) error
	mustEmbedUnimplementedDataIngestionServer()
}

// UnimplementedDataIngestionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataIngestionServer struct{}

func (UnimplementedDataIngestionServer) NotifyBFF(*NotifyBFFRequest, grpc.ServerStreamingServer[NotifyBFFResponse]) error {
	return status.Error(codes.Unimplemented, "method NotifyBFF not implemented")
}
func (UnimplementedDataIngestionServer) mustEmbedUnimplementedDataIngestionServer() {}
func (UnimplementedDataIngestionServer) testEmbeddedByValue()                       {}

// UnsafeDataIngestionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataIngestionServer will
// result in compilation errors.
type UnsafeDataIngestionServer interface {
	mustEmbedUnimplementedDataIngestionServer()
}

func RegisterDataIngestionServer(s grpc.ServiceRegistrar, srv DataIngestionServer) {
	// If the following call panics, it indicates UnimplementedDataIngestionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataIngestion_ServiceDesc, srv)
}

func _DataIngestion_NotifyBFF_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NotifyBFFRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataIngestionServer).NotifyBFF(m, &grpc.GenericServerStream[NotifyBFFRequest, NotifyBFFResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataIngestion_NotifyBFFServer = grpc.ServerStreamingServer[NotifyBFFResponse]

// DataIngestion_ServiceDesc is the grpc.ServiceDesc for DataIngestion service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataIngestion_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dataIngestion.DataIngestion",
	HandlerType: (*DataIngestionServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "NotifyBFF",
			Handler:       _DataIngestion_NotifyBFF_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "data-ingestion.proto",
}
